name: YARA Rule Naming Convention Check

on:
  pull_request:
    branches:
      - main
      - '**'  # This allows the workflow to run on all branches

jobs:
  check-naming:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run YARA rule naming convention check
      run: |
        # Find all YARA rule files and check if they meet the naming convention
        find . -name '*.yar' -o -name '*.yara' | while read file; do
          # Extract rule names from the file and check them
          grep -oP '^rule\s+\K\w+' "$file" | while read rule; do
            if [[ ! "$rule" =~ ^[a-z0-9_]+$ ]]; then
              echo "Rule '$rule' in file '$file' does not follow the naming convention. It should be lowercase with underscores between words."
              exit 1
            fi
          done
        done
